# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Programming Study
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://liangsongpeng.github.io" # the base hostname & protocol for your site

permalink: /:year/:month/:day/:title/

# other links
github_username: LiangSongpeng
email: liangsongpeng@outlook.com

description_footer: 梁嵩鹏的学习记录博客

# comments
# two ways to comment, only choose one, and use your own short name
# 两种评论插件，选一个就好了，使用自己的 short_name
duoshuo_shortname: #lspblog
disqus_shortname: liangsongpeng


